* Interpretability logics
  Hi, welcome. In this presentation I will talk about Generalised Veltman
  Semantics in Agda. The authors of the paper are Joost, Luka, and myself: Jan.
  So, let's get started.

  next part.

  To begin with, let me briefly introduce the concepts in the title. Generalised
  Veltman semantics are a kind of relational semantics for interpretability
  logics. We will come back to those in a second.

  Agda is a proof assistant based on dependent type theory. More on that at the
  second part of the presentation.


  The logic gl is the logic of provability which studies the behaviour of the
  provability predicate. In this logic we have two modal operators. The first
  one is box which stands for provability. And the second operator is diamond,
  which stands for consistency. Note that usually we define diamond in terms of
  box since saying that A is consistent is the same as saying that we cannot
  prove the negation of A.

  next part.

  Interpretability logics extend gl and they expand the language with an
  additional modal operator, the triangle, which stands for interpretability. We
  write A triangle B to mean that A interprets B. In interpretability logics the
  ultimate goal is to find a logic that describes the behaviour of
  interpretability in the same way as gl does it for provability.

  next part.

  What does A interprets B really mean?

  An interpretation of a theory A into a theory B is a translation star that
  maps the non-logical symbols in the language of A to formulas in the language
  of B so that if phi is a theorem of A, then the translation of phi is a
  theorem of B.
